dj3/urls.py
from django.contrib import admin
from app01 import views
from django.urls import path, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 部门管理
    path('depart/list/', views.depart_list),
    path('depart/add/', views.depart_add),
    path('depart/delete/', views.depart_delete),
    # http://127.0.0.1:8000/2/edit/
    path('depart/<int:nid>/edit/', views.depart_edit),
    path('test/', views.test),

    # 用户管理
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('user/<int:nid>/edit/', views.user_edit),
    path('user/<int:nid>/delete/', views.user_delete),

    # 靓号管理
    path('perttynum/list/', views.perttynum_list),
    path('perttynum/add/', views.perttynum_add),
    path('perttynum/<int:nid>/edit/', views.perttynum_edit),
    path('perttynum/<int:nid>/delete/', views.perttynum_delete),

    # 管理员管理
    path('admin/list/', views.admin_list),
    path('admin/add/', views.admin_add),
    path('admin/<int:nid>/edit/', views.admin_edit),
    path('admin/<int:nid>/delete/', views.admin_delete),
    path('admin/<int:nid>/reset/', views.admin_reset),

    # 登陆
    path('login/', views.login),
    path('logout/', views.logout),

    # 验证码
    path('img/code/', views.img_code),

    # 任务管理
    path('task/list/', views.task_list),
    path('task/ajax/', views.task_ajax),
    path('task/add/', views.task_add),

    # 订单管理
    path('order/list/', views.order_list),
    path('order/add/', views.order_add),
    path('order/delete/', views.order_delete),
    path('order/detail/', views.order_detail),

    # 数据统计
    path('chart/list/', views.chart_list),
    path('chart/bar/', views.chart_bar),
    path('chart/pie/', views.chart_pie),
    path('chart/line/', views.chart_line),

    #文件上传
    path('upload/list/',views.upload_list),
    path('depart/muti/',views.depart_muti),
    path('upload/form/',views.upload_form),
    path('upload/modelform/',views.upload_modelform),
    path('city/list/',views.city_list),
    path('city/add/',views.city_add),


    #设置media目录
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

]

app01/models.py
from django.db import models

# Create your models here.
class Admin(models.Model):
    '''管理员'''
    username = models.CharField(verbose_name='帐号',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=64)
    def __str__(self):
        return self.username

class DepartMent(models.Model):
    '''部门表'''
    title = models.CharField(verbose_name='标题',max_length=32)
    def __str__(self):
        return self.title
class UserInfo(models.Model):
    '''员工表'''
    name = models.CharField(verbose_name='姓名',max_length=32)
    password = models.CharField(verbose_name='密码',max_length=64)
    age = models.IntegerField(verbose_name='年龄')
    account = models.DecimalField(verbose_name='帐户余额',max_digits=10,decimal_places=2,default=0) #总数10，小数位2
    #creat_time = models.DateTimeField(verbose_name='入职时间')  #年月日时分秒
    creat_time = models.DateField(verbose_name='入职时间') #年月日

    #没约束
    #depart_id = models.BigIntegerField(verbose_name='部门ID')

    #有约束
    #查空
    #depart = models.ForeignKey(to='DepartMent',to_field='id',null=True,blank=True,on_delete=models.SET_NULL())
    #级联删除
    depart = models.ForeignKey(verbose_name='部门', to='DepartMent',to_field='id',on_delete=models.CASCADE)

    gender_choices = (
        (1,'男'),
        (2,'女')
    )
    gender = models.SmallIntegerField(verbose_name='性别',choices=gender_choices,default=1)

class PrettyNum(models.Model):
    '''靓号表'''
    #想要字段允许为空就加上 null=True,blank=True
    mobile = models.CharField(verbose_name='手机号',max_length=32)
    price = models.IntegerField(verbose_name='价格',default=0)
    level_choices=(
        (1,'一级'),
        (2, '二级'),
        (3, '三级'),
        (4, '四级'),
        (5, '五级')
    )
    level = models.SmallIntegerField(verbose_name='级别',choices=level_choices,default=1)
    status_choices = (
        (1,'未占用'),
        (2, '已占用')
    )
    status = models.SmallIntegerField(verbose_name='状态',choices=status_choices,default=1)

class Task(models.Model):
    '''任务管理'''
    level_choices=(
        (1,'紧急'),
        (2, '一般'),
        (3, '临时'),
    )
    title = models.CharField(verbose_name='标题',max_length=64)
    detail = models.TextField(verbose_name='任务详情')
    level = models.SmallIntegerField(verbose_name='级别',choices=level_choices,default=3)
    user = models.ForeignKey(verbose_name='负责人',to="Admin",to_field="id",on_delete=models.CASCADE,default=1)

class Order(models.Model):
    '''工单'''
    oid = models.CharField(verbose_name='订单号',max_length=64)
    title = models.CharField(verbose_name='名称',max_length=32)
    price = models.IntegerField(verbose_name='价格')
    status_choices = (
        (1,"待支付"),
        (2, "已支付")
    )
    status = models.SmallIntegerField(verbose_name='状态',choices=status_choices,default=1)
    admin = models.ForeignKey(verbose_name='管理员',to='Admin',on_delete=models.CASCADE,default=1) #级联删除，当管理员表删除订单也会删除

class Boss(models.Model):
    '''老板'''
    name = models.CharField(verbose_name='姓名',max_length=32)
    age = models.IntegerField(verbose_name='年龄')
    img = models.CharField(verbose_name='头像',max_length=128)

class City(models.Model):
    '''城市，基于modelForm的上传示例'''
    name = models.CharField(verbose_name='名称',max_length=32)
    count = models.IntegerField(verbose_name='人口')
    #FileField 数据库本质也是CharField,自动保存数据
    img = models.FileField(verbose_name='LOGO',max_length=128,upload_to='city/')

app01/views.py
import json
import random
from datetime import datetime
import requests
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from app01 import models
from app01.utils.pagelist import Pagination
from app01.utils.bootstrapmodelform import BootStrapModelForm, BootStrapForm
from app01.utils.encrypt import md5
from app01.utils.code import check_code
from io import BytesIO
import os
# 如果要用axaj发送post请求,导入csrf_exempt装饰器
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings


# Create your views here.
def depart_list(request):
    '''部门列表'''
    queryset = models.DepartMent.objects.all()
    return render(request, 'depart_list.html', locals())


def depart_add(request):
    '''新建部门'''
    if request.method == 'GET':
        return render(request, 'depart_add.html')
    # 获取post提交过来的数据
    title = request.POST.get('title')
    # 存到数据库
    models.DepartMent.objects.create(title=title)
    return redirect('/depart/list/')


def depart_delete(request):
    '''删除部门'''
    if request.method == 'GET':
        # 获取id
        # http://127.0.0.1:8000/depart/delete/?nid=2
        nid = request.GET.get('nid')
        models.DepartMent.objects.filter(id=nid).delete()
        return redirect('/depart/list/')


# 另一种传参方式
def depart_edit(request, nid):
    '''修改部门'''

    # 根据id获取数据
    if request.method == 'GET':
        row_object = models.DepartMent.objects.filter(id=nid).first()
        return render(request, 'depart_edit.html', locals())
    title = request.POST.get('title')
    models.DepartMent.objects.filter(id=nid).update(title=title)
    return redirect('/depart/list/')


def test(request):
    return render(request, 'test.html')


def user_list(request):
    '''用户列表'''
    userlist = models.UserInfo.objects.all()

    return render(request, 'user_list.html', locals())


#############ModelForm示例#############
from django import forms


class UserModelForm(forms.ModelForm):
    name = forms.CharField(min_length=2, label='用户名')  # 重写字段，控制字段输入长度

    class Meta:
        model = models.UserInfo
        fields = ['name', 'age', 'password', 'account', 'creat_time', 'depart', 'gender']
        # 添加一个插件，定义每个字段的表单属性
        widgets = {
            #     'name':forms.TextInput(attrs={"class":"form-control"}),
            "password": forms.PasswordInput(attrs={"class": "form-control", "placeholder": "请输入密码"})
            #     'age':forms.TextInput(attrs={'class':'form-control'}),
            #     'account': forms.TextInput(attrs={'class': 'form-control'}),
            #     'depart': forms.TextInput(attrs={'class': 'form-control'}),
            #     'gender': forms.TextInput(attrs={'class': 'form-control'}),
            #     'creat_time':forms.DateInput(attrs={'class':'form-control'})
        }

    # 批量定义字段表单属性
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if name == 'password':
                continue
            field.widget.attrs = {'class': 'form-control', 'placeholder': f'请输入:{field.label}'}


def user_add(request):
    '''新建用户,基于modelform版本的'''
    if request.method == 'GET':
        form = UserModelForm()
        return render(request, 'user_add.html', locals())

    # 用户POST提交，数据校验
    form = UserModelForm(data=request.POST)
    if form.is_valid():
        # 如果数据合法，保存到数据库
        # print(form.cleaned_data)
        form.save()
        return redirect('/user/list/')
    else:
        return render(request, 'user_add.html', locals())
        print(form.errors)


def user_edit(request, nid):
    '''编辑用户'''
    row_object = models.UserInfo.objects.filter(id=nid).first()
    if request.method == 'GET':
        # 根据id获取行数据对象
        form = UserModelForm(instance=row_object)
        return render(request, 'user_edit.html', locals())
    form = UserModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存用户输入的值，如果需要自定义可以
        # form.instance.字段名 = 值
        form.save()
        return redirect('/user/list/')
    return render(request, 'user_edit.html', locals())


def user_delete(request, nid):
    '''删除用户'''
    models.UserInfo.objects.filter(id=nid).delete()
    return redirect('/user/list/')


##################靓号管理####################
from django.core.validators import RegexValidator  # 正则验证
from django.core.exceptions import ValidationError  # 函数验证


class PerryNumForm(forms.ModelForm):
    # 设置手机号的正则表达式   验证手机号方式一
    # mobile = forms.CharField(
    #     label='手机号',
    #     validators=[RegexValidator(r'^1[3-9]\d{9}$','手机号格式错误')]
    # )
    class Meta:
        model = models.PrettyNum
        # fields = ['mobile','price','level','status'] #一般写法
        fields = "__all__"  # 所有的字段
        # exclude = ['level']  #排除level字段

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            if name == 'password':
                continue
            field.widget.attrs = {'class': 'form-control', 'placeholder': f'请输入:{field.label}'}

    # 验证手机号 方式二  函数命名 clean_字段名  ，可以验证是否存在之类的其他问题
    def clean_mobile(self):
        txt_mobile = self.cleaned_data["mobile"]
        exist = models.PrettyNum.objects.filter(mobile=txt_mobile).exists()  # 验证是否是已有数据
        if len(txt_mobile) != 11:
            raise ValidationError("格式错误！")
        if exist:
            raise ValidationError('手机号已存在！')
        return txt_mobile


def perttynum_list(request):
    '''靓号列表'''
    # 模拟数据
    # for i in range(300):
    #     models.PrettyNum.objects.create(mobile=f'1388888888{i}',price=88+i,level=1,status=1)

    # 查询结果
    data_dict = {}
    search_data = request.GET.get("q", "")

    if search_data:
        data_dict["mobile__contains"] = search_data

    queryset = models.PrettyNum.objects.filter(**data_dict).order_by('id')

    page_object = Pagination(request, queryset)

    page_queryset = page_object.page_queryset  # 分完页的数据
    page_string = page_object.html()  # 页码

    return render(request, 'perttynum_list.html', locals())


def perttynum_add(request):
    '''新建靓号'''
    if request.method == 'GET':
        form = PerryNumForm()
        return render(request, 'perttynum_add.html', locals())
    form = PerryNumForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/perttynum/list/')
    return render(request, 'perttynum_add.html', locals())


class PerryNumEditForm(forms.ModelForm):
    '''单独定义一个编辑的类'''
    # 设置手机号的正则表达式   验证手机号方式一
    # mobile = forms.CharField(
    #     label='手机号',
    #     validators=[RegexValidator(r'^1[3-9]\d{9}$','手机号格式错误')]
    # )
    mobile = forms.CharField(disabled=True, label='手机号')  # 设置手机号不可改

    class Meta:
        model = models.PrettyNum
        fields = ['mobile', 'level', 'status']  # 只显示部分字段
        # fields = "__all__"  #所有的字段
        # exclude = ['level']  #排除level字段

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, field in self.fields.items():
            # 字段中有属性则保留原来的属性，没属性加属性
            if field.widget.attrs:
                field.widget.attrs["class"] = 'form-control'
                field.widget.attrs["placeholder"] = f'请输入:{field.label}'
            else:
                field.widget.attrs = {'class': 'form-control', 'placeholder': f'请输入:{field.label}'}


def perttynum_edit(request, nid):
    '''编辑靓号'''
    row_object = models.PrettyNum.objects.filter(id=nid).first()
    if request.method == 'GET':
        form = PerryNumEditForm(instance=row_object)
        return render(request, 'perttynum_edit.html', locals())
    form = PerryNumEditForm(data=request.POST, instance=row_object)
    if form.is_valid():
        form.save()
        return redirect('/perttynum/list/')
    return render(request, 'perttynum_edit.html', locals())


def perttynum_delete(request, nid):
    '''删除靓号'''
    models.PrettyNum.objects.filter(id=nid).delete()
    return redirect('/perttynum/list/')


def admin_list(request):
    '''管理员列表'''
    info_dict = request.session["info"]

    qdata = models.Admin.objects.all()
    page_object = Pagination(request, qdata)
    queryset = page_object.page_queryset
    page_string = page_object.html()
    return render(request, 'admin_list.html', locals())


class AdminModelForm(BootStrapModelForm):
    confirm_password = forms.CharField(label='确认密码', widget=forms.PasswordInput)

    class Meta:
        model = models.Admin
        fields = ['username', 'password', 'confirm_password']  # 只显示部分字段
        widgets = {'password': forms.PasswordInput}
        # fields = "__all__"  #所有的字段
        # exclude = ['level']  #排除level字段

    def clean_password(self):
        pwd = self.cleaned_data.get("password")
        return md5(pwd)

    def clean_confirm_password(self):
        confirm = md5(self.cleaned_data.get("confirm_password"))
        pwd = self.cleaned_data.get("password")
        if confirm != pwd:
            raise ValidationError("两次密码输入不一致！")
        return confirm


def admin_add(request):
    '''添加管理员'''
    title = '添加管理员'
    form = AdminModelForm()
    if request.method == 'GET':
        return render(request, 'change.html', locals())
    form = AdminModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/admin/list/')
    return render(request, 'change.html', locals())


class AdminEditModelForm(BootStrapModelForm):
    class Meta:
        model = models.Admin
        fields = ['username']


def admin_edit(request, nid):
    '''编辑管理员'''
    row_object = models.Admin.objects.filter(id=nid).first()
    title = '编辑管理员'
    error_msg = '用户不存在！'
    if not row_object:
        return render(request, 'error.html', locals())
    if request.method == 'GET':
        form = AdminEditModelForm(instance=row_object)
        return render(request, 'change.html', locals())
    form = AdminEditModelForm(data=request.POST, instance=row_object)
    if form.is_valid():

app01/templates/error.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="alert alert-danger" role="alert">{{ error_msg }}</div>
    </div>
{% endblock %}

app01/templates/order_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px">
            <input type="button" value="新建订单(属性显示)" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            <input id="btnAdd" type="button" value="新建订单(JS显示)" class="btn btn-primary">
        </div>
    </div>

    <!-- 新建/编辑订单对话框 -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建</h4>
                </div>
                <div class="modal-body">
                    <div class="panel-body">
                        <form id="formAdd" method="post">
                            {% for field in form %}
                                <div class="form-group">
                                    <label>{{ field.label }}</label>
                                    {{ field }}
                                    <span class="error-msg" style="color: #e01111">{{ field.errors.0 }}</span>
                                </div>
                            {% endfor %}
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保 存</button>
                </div>
            </div>
        </div>
    </div>
    <!-- 删除对话框 -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <h4>是否确定删除？</h4>
                <p style="margin: 10px 0">删除后，所有关联的数据都将被删除！</p>
                <p style="text-align: right">
                    <button id="btnConfirmDelete" type="button" class="btn btn-danger">确 定</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
                </p>
            </div>
        </div>
    </div>
    <!-- 订单列表 -->
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                订单列表
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>订单号</th>
                        <th>名称</th>
                        <th>价格</th>
                        <th>状态</th>
                        <th>负责人</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in page_queryset %}
                        <tr uid="{{ obj.id }}">

                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.oid }}</td>
                            <td>{{ obj.title }}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.get_status_display }}</td>
                            <td>{{ obj.admin.username }}</td>
                            <td>
                                <input uid="{{ obj.id }}" type="button" class="btn btn-primary btn-xs btn-edit"
                                       value="编辑">
                                <input uid="{{ obj.id }}" type="button" class="btn btn-danger btn-xs btn-delete"
                                       value="删除">
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        var DELETE_ID;
        var EDIT_ID;
        $(function () {
            bindBtnAddEvent();
            bindBtnSaveEvent();
            bindBtnDeleteEvent();
            bindBtnConfirmDeleteEvent();
            bindBtnEditEvent();
        })

        function bindBtnAddEvent() {
            $("#btnAdd").click(function () {
                EDIT_ID = undefined;
                //清空对话框中的数据
                $("#formAdd")[0].reset()
                //设置对话框标题
                $("#myModalLabel").text("新建");
                $('#myModal').modal('show');
            })
        };

        function bindBtnSaveEvent() {
            $("#btnSave").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: "/order/add/",
                    type: "post",
                    data: $("#formAdd").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            //清空表单
                            $("#formAdd")[0].reset();
                            $('#myModal').modal('hide');

                            location.reload();
                        } else {
                            $.each(res.error, function (name, data) {
                                $("#id_" + name).next().text(data[0]);
                            })
                        }
                    }
                })
            })
        };

        function bindBtnDeleteEvent() {
            $('.btn-delete').click(function () {
                $('#deleteModal').modal('show');
                DELETE_ID = $(this).attr("uid");
            })
        };

        function bindBtnConfirmDeleteEvent() {
            $("#btnConfirmDelete").click(function () {
                $.ajax({
                    url: "/order/delete/",
                    type: "GET",
                    data: {
                        "uid": DELETE_ID,
                    },
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            // $('#deleteModal').modal('hide');
                            //使用JS删除当前行
                            //$("tr[uid='"+DELETE_ID+"']").remove();
                            //DELETE_ID=0;

                            //方式二
                            location.reload();
                        } else {
                            alert(res.eorror)
                        }
                    }
                })
            })
        };

        function bindBtnEditEvent() {
            $(".btn-edit").click(function () {
                //清空对话框中的数据
                $("#formAdd")[0].reset()
                var uid = $(this).attr("uid");
                EDIT_ID = uid;
                //共用新建的对话框
                //发送ajax请求获取当前行的数据
                $.ajax({
                    url: '/order/detail/',
                    type: "GET",
                    data: {uid: uid},
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            //将数据赋值给对话框
                            $.each(res.data,function (name,value){
                                $("#id_"+name).val(value);
                            })
                            //设置对话框标题
                            $("#myModalLabel").text("编辑");
                            $('#myModal').modal('show');
                        } else {
                            alert(res.eorror);
                        }
                    }
                })
            })
        };
    </script>
{% endblock %}

app01/templates/perttynum_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div style="margin-bottom: 10px" class="clearfix">
            <a class="btn btn-success" href="/perttynum/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新增靓号
            </a>

            <div style="float: right;width: 300px">
                <form method="get">
                    <div class="input-group">
                        <input type="text" class="form-control" name="q" placeholder="搜索手机号" value="{{ search_data }}">
                        <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                  </span>
                    </div><!-- /input-group -->
                </form>
            </div>
        </div>
        <div class="panel panel-default">

            <div class="panel-heading">
                <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
                靓号列表
            </div>

            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>手机号</th>
                        <th>价格</th>
                        <th>级别</th>
                        <th>状态</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for ob in page_queryset %}
                        <tr>

                            <th scope="row">{{ ob.id }}</th>
                            <td>{{ ob.mobile }}</td>
                            <td>{{ ob.price }}</td>
                            <td>{{ ob.get_level_display }}</td>
                            <td>{{ ob.get_status_display }}</td>
                            <td>
                                <a href="/perttynum/{{ ob.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                                <a href="/perttynum/{{ ob.id }}/delete/" class="btn-danger btn-xs">删除</a>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}

app01/templates/task_list.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                新增任务
            </div>
            <div class="panel-body">
                <form id="addForm">
                    {% for field in form %}
                        <div class="form-group" style="position: relative">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span class="error-msg"
                                  style="color: #e01111;position: absolute">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button id="btnAdd" type="button" class="btn btn-primary">添加</button>
                </form>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="panel panel-default">

            <div class="panel-heading">
                <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                任务列表
            </div>
            <div class="panel-body">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>标题</th>
                        <th>详情</th>
                        <th>级别</th>
                        <th>负责人</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for obj in page_queryset %}
                        <tr>

                            <th scope="row">{{ obj.id }}</th>
                            <td>{{ obj.title }}</td>
                            <td>{{ obj.detail }}</td>
                            <td>{{ obj.get_level_display }}</td>
                            <td>{{ obj.user.username }}</td>
                            <td>
                                <a href="#" class="btn btn-primary btn-xs">编辑</a>
                                <a href="#" class="btn-danger btn-xs">删除</a>
                            </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
            <nav aria-label="Page navigation">
            <ul class="pagination">
                {{ page_string }}
            </ul>
        </nav>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            //页面框架加载完成后，代码自动执行
            bindAddFormBtnEvent();
        })

        function bindAddFormBtnEvent() {
            $("#btnAdd").click(function () {
                $(".error-msg").empty();
                $.ajax({
                    url: '/task/add/',
                    type: "post",
                    data: $("#addForm").serialize(),
                    dataType: "JSON",
                    success: function (res) {
                        if (res.status) {
                            alert("添加成功！");
                            location.reload();

                        } else {
                            $.each(res.error, function (name, data) {
                                $("#id_" + name).next().text(data[0]);
                            })
                        }

                    }
                })
            })
        }

    </script>
{% endblock %}

app01/templates/upload_modelform.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container">

    </div>
{% endblock %}

app01/templates/user_add.html
{% extends 'layout.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap-datetimepicker.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">新建用户</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <label>{{ field.label }}</label>
                            {{ field }}
                            <span style="color: #e01111">{{ field.errors.0 }}</span>
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">提交</button>
                </form>
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap-datetimepicker.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/bootstrap-3.4.1/js/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_creat_time').datetimepicker({
                format: 'yyyy-mm-dd',
                startDate: '0',
                language: "zh-CN",
                autoclose: true
            });
        })
    </script>
{% endblock %}